<?php
  $lang['number']		= 'Invoice';
  $lang['date'] 		= 'Billing Date';
  $lang['time']			= 'Billing Time';
  $lang['vehicleNumber'] 			= 'Vehicle No.';
  $lang['mileage'] 	= 'Vehicle Mileage';
  $lang['tin'] 			= 'TIN No.';
  $lang['pan'] 			= 'PAN No.';
  $lang['to'] 			= 'Billing to';
  $lang['from'] 		= 'Billing from';
  $lang['product'] 		= 'Product';
  $lang['serviceItem'] 	= 'Particulars';
  $lang['qty'] 			= 'Qty';
  $lang['price'] 		= 'Price';
  $lang['discount'] 	= 'Discount';
  $lang['vat'] 			= 'Vat';
  $lang['total'] 		= 'Total';
  $lang['page'] 		= 'Page';
  $lang['page_of'] 		= 'of';
?>