<?php
  $lang['number']		= 'Invoice';
  $lang['date'] 		= 'Billing date';
  $lang['time']			= 'Billing time';
  $lang['due'] 			= 'Vehicle no.';
  $lang['to'] 			= 'Billing to';
  $lang['from'] 		= 'Billing from';
  $lang['product'] 		= 'Product';
  $lang['qty'] 			= 'Qty';
  $lang['price'] 		= 'Price';
  $lang['discount'] 	= 'Discount';
  $lang['vat'] 			= 'Vat';
  $lang['total'] 		= 'Total';
  $lang['page'] 		= 'Page';
  $lang['page_of'] 		= 'of';
?>